const typesUser = {
    LOG_IN_START: 'LOG_IN_START',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_AUTH_VALUE: 'RESET_AUTH_VALUE',

};

export default typesUser;