const typesUser = {
    LOG_IN_START: 'LOG_IN_START',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    USER_CHECK_SESSION: 'USER_CHECK_SESSION',
    LOG_OUT_START: 'LOG_OUT_START',
    LOG_OUT_SUCCESS:'LOG_OUT_SUCESS',
    REGISTER_START: 'REGISTER_START,',
    ERROR_USER:'ERROR_USER',


    
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_AUTH_VALUE: 'RESET_AUTH_VALUE',

};

export default typesUser;